# Generated by Django 5.2.5 on 2025-10-20 12:44

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users_app.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.UUIDField(db_column='id_rol', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre_rol', max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. A valid email address.', max_length=150, null=True, unique=True, verbose_name='email')),
                ('password', models.CharField(default='12345678', max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, db_column='nombre', max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enable_bloked', models.BooleanField(default=True)),
                ('credits', models.PositiveIntegerField(db_column='coins', default=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BANEADO', 'Baneado')], db_column='estado', default='ACTIVO', help_text='Estado del usuario: ACTIVO o BANEADO.', max_length=10)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('Time_espera', models.PositiveIntegerField(default=0, null=True)),
                ('antispam', models.PositiveIntegerField(default=60)),
                ('user_keys', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_role', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.role')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
            managers=[
                ('objects', users_app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogBlockedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_login_attempt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginIncorrect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
