"""
Django settings for plataformaapis project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from config.utils import get_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR_MANAGE = Path(__file__).resolve().parent.parent.parent
BASE_APP = Path(__file__).resolve().parent.parent.parent.parent
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("SECRET_KEY")


# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


LOCAL_APPS = [
    "users_app",
    "core_app",
]


THIRD_PARTY_APPS = [
    "corsheaders",
    "inertia",
    "django_vite",
    "hcaptcha_field",
    "django_ratelimit",
    "rest_framework",
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

SILENCED_SYSTEM_CHECKS = ["django_ratelimit.E003", "django_ratelimit.W001"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "inertia.middleware.InertiaMiddleware",
    "config.middleware.inertia_share.inertia_share",
    "config.middleware.force_single_session.force_single_session",
    "config.middleware.role_module_permission_middleware.role_module_permission_middleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8080",
    "http://127.0.0.1:8000",
    # Agrega más dominios si es necesario
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR_MANAGE / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# CUSTOM USER MODEL
AUTH_USER_MODEL = "users_app.User"
USERNAME_FIELD = "email"
REQUIRED_FIELDS = ["username"]
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-pe"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR_MANAGE / "frontend" / "dist"]

# Vite
DJANGO_VITE_ASSETS_PATH = BASE_DIR_MANAGE / "frontend" / "dist"
# This tells Django to load the manifest from the front end build folder
# Comment it out if you run python manage.py collectstatic
DJANGO_VITE_MANIFEST_PATH = DJANGO_VITE_ASSETS_PATH / "manifest.json"
DJANGO_VITE_DEV_SERVER_PORT = 5173
STATICFILES_DIRS.append(DJANGO_VITE_ASSETS_PATH)

# Inertia
APP_NAME = "editorial_atlantico"
CSRF_HEADER_NAME = "HTTP_X_XSRF_TOKEN"
CSRF_COOKIE_NAME = "XSRF-TOKEN"
INERTIA_LAYOUT = "app.html"
INERTIA_VERSION = "1.0"
INERTIA_SSR_ENABLED = False
INERTIA_SSR_URL = "http://localhost:13714"

# Duración de la sesión en segundos (3 horas)
SESSION_COOKIE_AGE = 10800

# Aumentar el timeout para peticiones
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # Para formularios grandes

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# HCAPTCHA
HCAPTCHA_SITEKEY = get_secret("HCAPTCHA_SITEKEY")
HCAPTCHA_SECRET = get_secret("HCAPTCHA_SECRET")
HCAPTCHA_PROXIES = {
    "http": "http://127.0.0.1:8000",
}
HCAPTCHA_TIMEOUT = 5
HCAPTCHA_JS_API_URL = "https://hcaptcha.com/1/api.js"
HCAPTCHA_VERIFY_URL = "https://hcaptcha.com/siteverify"


# RATELIMIT
RATELIMIT_USE_CACHE = "default"
RATELIMIT_ENABLE = True
RATELIMIT_SKIP_CHECKS = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
            "formatter": "verbose",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "WARNING",
            "propagate": True,
        },
        "myapp": {  # Logger personalizado para tu aplicación
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

CACHES = {
  'default': {
      'BACKEND': 'django_redis.cache.RedisCache',
      'LOCATION': REDIS_URL,
      'OPTIONS': {
          'CLIENT_CLASS': 'django_redis.client.DefaultClient',
          "MAX_ENTRIES": 1000
      },
      'KEY_PREFIX': 'django_cache',
      'TIMEOUT': 300,  # 5 minutos por defecto
  }
}

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = get_secret("EMAIL_HOST")
EMAIL_PORT = get_secret("EMAIL_PORT")
EMAIL_USE_TLS = get_secret("EMAIL_USE_TLS")
EMAIL_USE_SSL = get_secret("EMAIL_USE_SSL")
EMAIL_HOST_USER = get_secret("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = get_secret("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
